### ISSUE TITLE
Syntax highlighting broken with `ftdetect`

### ISSUE THREAD

**Issue by arzg** [lifepillar/vim-outlaw#1]
```bash
$ mkdir -p ~/.vim/after/ftdetect
$ echo "autocmd BufNewFile,BufRead *.outline set filetype=outlaw" > ~/.vim/after/ftdetect/outlaw.vim
$ echo "=== My biography
    The secret of a long life is trying not to shorten it.
    === Travel to the East
        === The telegram" > test.outline
$ vim test.outline
```

Now press `zi` to open all folds and, for me at least, `=== Travel to the East` is not highlighted until I manually run `set filetype=outlaw`.

**Comment by lifepillar** [comment]
I have copy-pasted your example, but I cannot reproduce your issue. Given the symptoms, the most likely cause is that the line that is not highlighted does not have the right indentation.

Btw, I would write the ftdetect file to `~/.vim/ftdetect/outlaw.vim` rather than putting in an `after` directory.

**Comment by arzg** [comment]
> the most likely cause is that the line that is not highlighted does not have the right indentation

Interesting, because manually setting `ft=outlaw` fixes the issue. Wouldn’t that imply that it is not the file that is wrong, but rather that some kind of mechanic is activated when manually running `set filetype` that isn’t by the ftdetect I specified?

> I would write the ftdetect file to `~/.vim/ftdetect/outlaw.vim`

Is that because this plugin does not define a ftdetect, so there’s nothing to override?

**Comment by lifepillar** [comment]
Please try this:

1. Open your document, make sure that it is *not* highlighted correctly and take note of these values:

```vim
:setl shiftwidth?
:setl tabstop?
:setl softtabstop?
:setl expandtab?
```

Then, execute `:set ft=outlaw`, make sure that highlighting *is* changed, and check those values again. Are they the same?

>I tried putting this into `~/.vim/ftplugin/outlaw.vim`, to no avail

Most likely, you need to put your settings in `~/.vim/after/ftplugin/outlaw.vim` instead.

>I would write the ftdetect file to `~/.vim/ftdetect/outlaw.vim`
>Is that because this plugin does not define a ftdetect, so there’s nothing to override?

Yes. In fact, I might add an ftdetect file to the plugin.

**Comment by arzg** [comment]
Ok, here are the steps I’m following:

```bash
$ rm -rf ~/.vim*
$ mkdir -p ~/.vim/pack/bundle/start
$ cd ~/.vim/pack/bundle/start
$ git clone https://github.com/lifepillar/vim-outlaw.git
$ cd ~/.vim
$ mkdir ftdetect
$ echo "autocmd BufNewFile,BufRead *.outline set filetype=outlaw" > ftdetect/outlaw.vim
$ cd /tmp
$ echo "=== My biography
    The secret of a long life is trying not to shorten it.
    === Travel to the East
        === The telegram" > test.outline
$ vim test.outline

```viml
:normal! zi " it is incorrectly highlighted
:setl shiftwidth? " 8
:setl tabstop? " 8
:setl softtabstop? " 0
:setl expandtab? " noexpandtab
:set filetype=outlaw " no change in values or highlighting
:q
```

$ cd ~/.vim
$ mkdir -p after/ftplugin
$ echo "setlocal textwidth=80
setlocal shiftwidth=4
setlocal tabstop=4
setlocal softtabstop=0
setlocal expandtab" > after/ftplugin/outlaw.vim
$ cd /tmp
$ vim test.outline

```viml
:normal! zi " it is still incorrectly highlighted
:setl shiftwidth? " 8
:setl tabstop? " 8
:setl softtabstop? " 0
:setl expandtab? " noexpandtab
:set filetype=outlaw " no change
```

Looks like `after/ftplugin/outlaw.vim` isn’t applying for some reason? However, running this:

```viml
:source ~/.vim/after/ftplugin/outlaw.vim
:set filetype=outlaw
```

fixes the issue.

**Comment by lifepillar** [comment]
>Ok, here are the steps I’m following:

Now I can reproduce it. In your first example, the highlighting issue is because your document uses four spaces for indentation,  but Vim's default is eight spaces. Resetting the filetype does not change anything, as expected.

The second example surprises me, though. Differently from you, the settings in `after/ftplugin/outlaw.vim` are picked up; nonetheless, the third line is not highlighted. Even more suprisingly, putting the settings in the modeline does not fix it either. So, there's definitely something wrong going on. I'll dig into it then come back to you.

**Comment by lifepillar** [comment]
Found the culprit. When you open an `.outlaw` documents, Vim reads:

```
 1: ~/.vim/pack/bundle/start/vim-outlaw/syntax/outlaw.vim
 2: ~/.vim/pack/bundle/start/vim-outlaw/ftplugin/outlaw.vim
 3: ~/.vim/after/ftplugin/outlaw.vim
 4: ~/.vim/pack/bundle/start/vim-outlaw/indent/outlaw.vim
```

in that order. The syntax file is read before the other files and also before the modeline is interpreted. But the syntax files uses the values of `shiftwidth` (and `tabstop`, if `shiftwidth` is zero). So, a temporary workaround is to set `shiftwidth` in your `vimrc`.

I'll see how I can fix that.

**Comment by arzg** [comment]
> Differently from you

To be totally honest I’m not entirely sure what’s going on with my Vim – first setting `filetype` again fixes it, then not, and now this. I’ve accumulated quite a bit of junk, so I think I might reset. Before the last reset I had an issue where `git branch` would not print any output no matter what unless I piped it through `grep ''`! This issue was with both the system and Homebrew’s git, and disappeared mysteriously after resetting :/

> Found the culprit.

Impressive! Glad you managed to find it so quickly.

> I'll see how I can fix that.

Thank you for putting so much time into this issue. Do you have any ideas how this could be resolved?

> an `.outlaw` document

Do you think it would be good to handle all of this for the user by:

1. **Creating a default ftdetect.** Some possible candidates for this include `.otl`  and `.oln` [from VimOutliner](https://github.com/vimoutliner/vimoutliner/blob/aad0a213069b8a1b5de91cca07d153fc8352c957/ftdetect/votl.vim#L22), or maybe `.outlaw` instead.
2. **Setting indentation settings.** I’m not aware of the best practice in this area (whether it is recommended for syntax plugins to modify indentation settings or if it is best to leave it up to the user), but I would personally prefer having this kind of thing done automatically instead of having to copy-paste a modelling into every outline. Would you say that using something like [vim-editorconfig](https://github.com/sgur/vim-editorconfig) would also work for now (since I already use it)?

**Comment by lifepillar** [comment]
I think that the best fix is by adding an option to set the desired indentation and let the plugin figure out the rest. I will also add the ftdetect.

**Comment by lifepillar** [comment]
The current master recognizes `.outl` and `.outlaw` files as Outlaw buffers. Besides, there is a new option that the user may set to define the desired indentation level in Outlaw buffers (no need to worry about `shiftwidth`, `tabstop` and `softtabstop`: they are set locally by the plugin). Putting this line in your `vimrc`:

```vim
let g:outlaw_indent = 4
```
should fix your issue. Feel free to reopen if that is not the case.

**Comment by arzg** [comment]
Thank you for finding a solution to this!
