### ISSUE TITLE
Colorscheme on screenshot

### ISSUE THREAD

**Issue by kristijanhusak** [lifepillar/vim-outlaw#3]
Hi,

can you tell me what's the colorscheme on the screenshot in readme?

![screenshot](https://raw.githubusercontent.com/lifepillar/Resources/master/outlaw/outlaw-taskPaper.png)

**Comment by lifepillar** [comment]
Sure. It’s my [WWDC17](https://github.com/lifepillar/vim-wwdc17-theme).

**Comment by kristijanhusak** [comment]
Thanks!
